### ISSUE TITLE
Add the ability to use an incipit as a query

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#139]
Place a link or icon next to incipits to perform a search using that incipit.

Related to #137

**Comment by lpugin** [comment]
Passing the key signature now works great. I do think we need to pass the clef and time signature too because otherwise it looks weird. See

https://dev.rism.online/search?n=24%2CCG%2FAG%2FFxF%2F4G--%2FGB%2F%27C%2CE%2F%7B8.6FE%7D4E-%2F&mode=incipits&ik=n

I understand some values would not be selected in the drop-down lists (e.g. a C-2 clef), but that would be fine in my opinion. As far as I tested it would work

https://dev.rism.online/search?mode=incipits&page=1&n=24%2CCG%2FAG%2FFxF%2F4G--%2FGB%2F%27C%2CE%2F{8.6FE}4E-%2F&ic=C-2&it=3%2F4

**Comment by ahankinson** [comment]
This is now available. Further adjustments to this function should have dedicated issues. Closing.

**Comment by lpugin** [comment]
Passing the clef and the time signature (see my last comment) should still be addressed. Any problems with this?

**Comment by ahankinson** [comment]
The "use this incipit as a search" adds the clef and key signature, but not the time signature. It seems to work OK without it?

**Comment by ahankinson** [comment]
Sorry -- doesn't pass the clef, only the key signature. 

I guess it depends on whether you think it should provide the exact result, or the matching pitches. My view is that you can use it to find quotations or similar results (which needs the key signature, but doesn't need the others).

**Comment by ahankinson** [comment]
See, for example, this search: 

https://rism.online/search?n=%3D3%2F4-%27%27C4.E8E%2F2E4-E%2F&mode=incipits&ik=n

Which was performed when searching for this incipit:

https://rism.online/search?mode=incipits&page=1&rows=20#sources-450006089-incipits-1.1.2

**Comment by lpugin** [comment]
Yes, I get that. It does look terribly ugly with low clefs and very weird to have a C indication with measures in 3/4.

**Comment by ahankinson** [comment]
Presumably, though, if it's the "tune" that's important then it doesn't matter what instrument plays it?

**Comment by ahankinson** [comment]
Time signature is obviously a different matter, but it would similarly be weird to have "c" not show up with a query of "4/4".

**Comment by lpugin** [comment]
Sorry, but I cannot read this ;-)
https://dev.rism.online/search?n=4%2C%2CCEC%2FFGA%2FFFG%2F&mode=incipits&ik=n
