### ISSUE TITLE
Consider IIIF manifests as ‘digitizations’ as soon as there is a IIIF viewer available on RISM online

### ISSUE THREAD

**Issue by baccia** [rism-digital/rism-online-issues#177]
The digitization toggle should look for links in the 865 also with a value of IIIF manifest, as soon as an embedded IIIF viewer (diva) is implemented on RO.
Example query: 
https://rism.online/search?q=dialogo&mode=sources&fq=composer%3ACossoni%2C%20Carlo%20Donato%20(1623-1700)&fb=composer%3Aunion&page=1
These are three child records of parent records with IIIF manifests, e.g.:
https://rism.online/sources/400011734
They should eventually show up as results when the digitization filter is applied.

**Comment by ahankinson** [comment]
@lpugin and I discussed this. I think in the first instance we should set up a IIIF Viewer and automatically link the IIIF manifests to that so that people can view the images on RISM Online. In the future we'll probably have a tab view with a better-integrated IIIF viewer.

As for the IIIF Viewers, I think it's a choice between TIFY and Universal Viewer:

https://tify.rocks

https://universalviewer.io

@lpugin any preferences? Looks like TIFY is quite nice and lightweight. (I'm deliberately not choosing Diva because I think it needs a bit of work atm.)

**Comment by lpugin** [comment]
I did use TIFY for a course and it was very nice and very light. So more a feedback than really a preference because I have not much experience with Universal Viewer.

**Comment by lpugin** [comment]
(I think the look and feel of TIFY would match the rism.online one better than UV)
