### ISSUE TITLE
Icon for voice instrument a bit confusing

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#193]
![image](https://user-images.githubusercontent.com/689412/173513971-99f1cb3d-6664-4b8f-9a51-8985632adea2.png)

Suggestions for something else
https://fontawesome.com/v5/icons/mandolin?s=solid
https://fontawesome.com/v5/icons/comment-music?s=solid
https://fontawesome.com/v5/icons/clarinet?s=solid

**Comment by ahankinson** [comment]
I was hesitating to add a specific instrument, because having a Violin icon next to a voice indicator might be confusing.

I was thinking about this one: https://fontawesome.com/icons/list-music?s=solid

Since it seems to communicate music, but in some sort of "line" or "classification" form... I know it's supposed to be a "list" but in this case I think it works. Thoughts?

**Comment by lpugin** [comment]
Looks good to me

**Comment by BaMikusi** [comment]
Yeah, seems abstract enough.
