### ISSUE TITLE
Selecting a key signature facet with [ ] fails

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#195]
Eg, `xF[C]` yields a 500

Question: don't we want to remove the [ ] from the facet list? That would reduce the number of values. I am not sure filtering by `xF[C]` does really make sense, does it?

**Comment by ahankinson** [comment]
I'm generally very conservative about "cleaning up" the data for search. My thinking is that if it's in the data, then it should be presented that way in the search interface since it was entered in the catalogue for, presumably, a very specific reason.

I can fix the "[]" issue causing a 500, but I'm less enthused about dropping them altogether.

**Comment by lpugin** [comment]
(It was not meant to be a cleaning up of the data but rather a regrouping of values that can be seen are identical from a search point of view)
