### ISSUE TITLE
Suggestions for front page background images

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#198]
If there are suggestions, even just a theme or a "feeling", for the background images on the front page, please comment here.

We need four images:

 - Source
 - People
 - Institutions
 - Incipits

Some guidelines:
 - They should be thematically related to the section (e.g., don't make a person the prominent image for "Sources")
 - Depending on the user's screen, the image may be partially or wholly covered. The left side of the image will be covered almost always, the right side will expand to fill the space on their monitor.
 - They should be available with a Creative Commons license that allows re-use. Attribution is fine (I have a to-do to create an attribution for the images in the lower-right corner.)

**Comment by lpugin** [comment]
All sensible. I would also suggest that we go for all colour images or all greyscale, but not mix them.

**Comment by lpugin** [comment]
Here are some proposals for colour images. Some of them would need to be cropped in order to remove the border. It would be good to have a size to be at least 2560 wide and 1440 height.

### Sources

#### Madrigali di Luzzasco Luzzaschi
https://www.loc.gov/resource/ihas.200154752.0/?sp=15 [or another page]
corresponding to [990038751](https://rism.online/sources/990038751)
I like it because it is a print that does also look like a manuscript. And it is by Verovio ;-)

### Persons

Both options have a person on the right of the image in order to make sure something appropriate appears on the side of the facet block

#### Liszt am Flügel
https://fr.wikipedia.org/wiki/Fichier:Josef_Danhauser_Liszt_am_Fl%C3%BCgel_1840_01.jpg
https://upload.wikimedia.org/wikipedia/commons/e/e0/Josef_Danhauser_Liszt_am_Fl%C3%BCgel_1840_01.jpg
which we can make point to [Danhauser](https://rism.online/people/50045288) or [Liszt](https://rism.online/people/107196), or even Beethoven..

#### Duarte family
https://commons.wikimedia.org/wiki/File:Gonzales_Coques_-_Portrait_of_the_Duarte_family.jpg
https://upload.wikimedia.org/wikipedia/commons/d/d1/Gonzales_Coques_-_Portrait_of_the_Duarte_family.jpg
which we can make point to [Leonora Duarte](https://rism.online/people/30114814) (it is nice to have a female composer)

### Institutions

#### Stiftsbibliothek Kloster Einsiedeln
https://upload.wikimedia.org/wikipedia/commons/b/b3/Einsiedeln_Abbey_Library.JPG
https://upload.wikimedia.org/wikipedia/commons/5/51/Stiftsbibliothek_Kloster_Einsiedeln.JPG
corresponding to [CH-E](https://rism.online/institutions/30000006)

### Incipits

#### Katalog der Lucas Sarasin’schen Musiksammlung
https://www.e-manuscripta.ch/bau/content/zoom/659450
corresponding to [406002382](https://rism.online/sources/406002382)
Because the text is on the left and the music on the right it seems like a perfect fit for our needs. Plus the source itself is in RISM

**Comment by BaMikusi** [comment]
I like the train of thought behind each one of these, but two comments on the Danhauser painting: (1) For our purposes, Liszt is looking in the wrong direction, and the image is IMO too famous to simply be flipped; (2) as a background image, which is not supposed to steal the show, less famous/recognizable people might be more appropriate.

**Comment by ahankinson** [comment]
I just reviewed the images.

- The Marenzio print looks OK. I was able to download an uncompressed TIFF, so I'll try it and see how it looks. 
- The Duarte family image is nice, but the largest available image still has quite a few JPEG artifacts. I can't seem to find a higher-resolution download that doesn't have annoying watermarks on it.
- I'm not particularly taken by the Einsiedeln images... They just look a bit lifeless; I think they've been normalized to sRGB, which really constrains the colour palette making colours look just a bit "meh". Of the two I think the first is better. I can try that. It also suffers from having JPEG artifacts at higher magnification, but it's less obvious than the Duarte family one.
- The incipits suggestion looks fine. It will probably need cropping because of the large black border around the page.

I didn't review the Liszt one, due to @BaMikusi's comments.

**Comment by ahankinson** [comment]
OK, so having tried them, here are a few screenshots.

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/163183/178468113-66a211bc-1927-4b40-a847-3d8ed65f7950.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/163183/178468151-e0081e00-e003-46a8-88de-68cbe383d95e.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/163183/178468209-eb063208-89c8-45b7-be51-7363565d27e0.png">

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/163183/178468258-9d9deff1-8fb9-46b9-88df-f5ac70df2536.png">

Thoughts?

**Comment by lpugin** [comment]
From what I can see here it seems that the other one from Einsiedeln would be better. Could you try it? If somebody wants to look at alternatives, I would say that persons is the one we could do with something different.

**Comment by ahankinson** [comment]
Here is a screenshot with the alternative Einsiedeln image; the JPEG artifacts are really bad on this once it's compressed down from the original (to try and get it to ~250kb, which I've set as a limit for each of the images so that they don't slow down the site loading.)

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/163183/178912677-f0d36624-b2c6-4b0f-be04-64a5982dba6a.png">

**Comment by ahankinson** [comment]
Here's a close-up:

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/163183/178913017-101b08fe-c4e8-47dd-b4f8-55f59e4fb9b4.png">

**Comment by ahankinson** [comment]
Will launch with the current images; updates can open new issues.
