### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/rism-online-issues#207]
From feedback:

"I also noted that sometimes entries on three pages are promised (for instance with the search words "Josquin Desprez Petrucci"), but no second or third page is available." [Indeed, in this case rism.online at first seems to believe that there will be 54 hits, and accordingly indicates two more pages of them, but once you click on the arrow, an empty page appears and the number of hits indicated on the right drops to 17. Whereby on the very first page in fact already 20 hits were shown.]

**Comment by lpugin** [comment]
It seems that the problem is that a `+` is added between the words when the next page is loaded

**Comment by lpugin** [comment]
Original search (3 pages with 54 results)

![image](https://user-images.githubusercontent.com/689412/177987213-56516d27-c5f9-4d24-bff3-4b35254eefe7.png)


Page 2 (nothing showing because the number of result is now 17)

![image](https://user-images.githubusercontent.com/689412/177987149-8d2bf312-1ec2-4599-adad-b46206a20941.png)
