### ISSUE TITLE
Active filters unclear when clicking from a URL

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism-online-issues#238]
If you click on a URL from a friend then it isn't immediately clear from the search interface what filters are active. For https://dev.rism.online/search?mode=sources&fq=num-holdings%3A1&fq=sigla%3AUS-U&fb=sigla%3Aintersection&page=1&rows=20 all filters are closed so you have to click through all of them before seeing where the filters are applied. I wonder if it would be possible to make the active filters more visible, maybe through highlighting or a symbol next to the filter, or summarizing the search somewhere at the top. But I don't know if that could get too confusing with complicated searches.

**Comment by lpugin** [comment]
Always opening filters given in the URL might also be problematic. For example, if a user selects something, and then wants the facet to be closed because he wants to focus on other things. For example, looking at "prints", and then closing it because he wants to use the space for additional facets. If the "print" facet keeps opening every time a new filter is applied this will be annoying too. 

We probably all agree that this is not a high priority, but I think we can either have an option to (re-)open all facets, or (better but more complicated) (re-)open all facets applied. 

Alternatively, we can have a summary indication of the facets currently applied.
