### ISSUE TITLE
Rename "Record URI (Permalink)"

### ISSUE THREAD

**Issue by lpugin** [rism-digital/rism-online-issues#239]
Currently, the preview shows the link to the record with the label "Record URI (Permalink):" Some people have reported not having clicked on it because they did not think it was the link for the (full) record. We should think about a more "inviting" label

**Comment by jenniferward** [comment]
In Muscat I call it the "Full record view" (just in the prose, not as a label). But I think you are using the same term in two places, the preview and on each record? Maybe we can have two labels:
Here https://rism.online/search?mode=sources&page=1&rows=20#sources-240001248
it would make sense to have "Full record view (Permalink): LINK"
 And at the bottom of each full record
Permalink: LINK

**Comment by ahankinson** [comment]
I can put "Full record view" in the preview at the top, replacing the "Record URI (Permalink)" label. 

I will keep "Record URI (Permalink)" on the bottom of the full record views. I want to keep "URI" because I want to communicate that is both a URL and a URI, and that the two are the same. So I won't change that.

I think including the URI in the name is important for when our data gets used in a Linked Data context, since triples are formed using URIs, not URLs! Admittedly the audience for it is smaller, but I still think we need to signal that there isn't a separate public record **identifier** that people should be using in that context. 

This is in contrast to the OPAC. `https://opac.rism.info/search?id=1001197149&View=rism` is the URL (permalink) but `http://data.rism.info/id/rismid/1001197149` as the RDF URI for the same record!

In fact, the OPAC `data.rism.info` URI goes through four different URL redirects if you load it, and they do not exactly correspond to the "permalink" that is cited... 

 - `http://data.rism.info/id/rismid/1001197149`
 - `https://data.rism.info/id/rismid/1001197149`
 - `https://data.rism.info/metaopac/search?View=rism&db=251&id=1001197149`
 - `https://opac.rism.info/metaopac/search?View=rism&db=251&id=1001197149`

This is (IMO) a bit messy, and not really how it's supposed to work.

It may also be useful context to know that we've registered `rism:` as a compact identifier prefix with https://identifiers.org. What this means is that, in some contexts you can replace the constant "https://rism.online" part with just `rism:`.

So:

 - "rism:sources/1001197149" -> "https://rism.online/sources/1001197149"
 - "rism:people/72637" -> "https://rism.online/people/72637"

This is useful in the JSON-LD world, where these prefixes can be automatically expanded and aliased. It's my hope that this sort of shorthand will be useful when we get around to linking RISM Online records in sites like Wikidata.
